//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHost.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public System.Guid BookingId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ParkingSpaceId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal MonthlyFee { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual FreeParkingSpace FreeParkingSpace { get; set; }
        public virtual User User { get; set; }
    }
}
