//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHost.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSpace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkingSpace()
        {
            this.UserToParkingSpaces = new HashSet<UserToParkingSpace>();
        }
    
        public System.Guid ParkingSpaceId { get; set; }
        public System.Guid ParkingSpaceFeeId { get; set; }
        public string ParkingSpaceNumber { get; set; }
    
        public virtual ParkingSpaceFee ParkingSpaceFee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserToParkingSpace> UserToParkingSpaces { get; set; }
    }
}
