//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHost.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public System.Guid PaymentId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public decimal PaidAmount { get; set; }
    
        public virtual User User { get; set; }
    }
}
