//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHost.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToParkingSpace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserToParkingSpace()
        {
            this.FreeParkingSpaces = new HashSet<FreeParkingSpace>();
        }
    
        public System.Guid UserToParkingSpaceId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ParkingSpaceId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FreeParkingSpace> FreeParkingSpaces { get; set; }
        public virtual ParkingSpace ParkingSpace { get; set; }
        public virtual User User { get; set; }
    }
}
